### ISSUE TITLE
CORS configuration

### ISSUE THREAD

**Issue by AknEp** [danielgtaylor/apisprout#10]
Hi, I'm using this apisprout in web development project.

I'm happy if it has configuration to add `Access-Control-Allow-Origin` HTTP Header.
Currently, I have to add some proxy.

**Comment by khayhurst** [comment]
I was able to make the changes and recompile according to pull request #6 by arthuroz. Tested and working.

**Comment by danielgtaylor** [comment]
This is fixed as of 2f06f8b5491f114180fa461c5d1b8e652f6bfdd5 and enabled by default now. No need to pass any special flags or anything.
