### ISSUE TITLE
Running on local file

### ISSUE THREAD

**Issue by MicMicMon** [danielgtaylor/apisprout#12]
I try to run the command in the README

`docker run -p 8000:8000 -v $(pwd)/open_api.json:/api.json danielgtaylor/apisprout /api.json`

but I get:

`open /api.json: permission denied`

I don't know much about `docker` usage, is there a quick way to get around that issue?

**Comment by kyledinh** [comment]
I'm on a Mac.

Try to use the whole path from "/" something like this:
`docker run -p 8000:8000 -v /Users/kyle/where/my/file/is/my-version.json:/api.json kyledinh/apisprout /api.json`

**Comment by danielgtaylor** [comment]
@MicMicMon did using the full path fix this? Are your local permissions set strangely? You could try to run a shell instead of `apisprout` and inspect what `/api.json` looks like in the container.

**Comment by MicMicMon** [comment]
Yeah, `($pwd)` already is the full path, so doesn't help :(
The file is correctly found, because if I do `/api.json-not-existing` instead, I get a file missing error which is expected.

Nothing strange that I know of on the file permissions.

I don't know Docker yet, will learn in the near future, I will be able to try more.

I will try your suggestion, that would be something like
```
docker run -p 8000:8000 -v $(pwd)/open_api.json:/api.json bash ls -all /
```
right? Don't have Linux at hand right now.

**Comment by timaschew** [comment]
I'm using macOS and Docker version 18.09.1, build 4c52b90 

And I get this error when trying to start the docker container
```
2019/02/02 08:29:08 invalid character 'o' looking for beginning of value
```

**Comment by danielgtaylor** [comment]
I'm going to close this, as we have users confirming it is working. Please feel free to reopen if you are still having issues.
