### ISSUE TITLE
Provide endpoint to reload definition

### ISSUE THREAD

**Issue by timaschew** [danielgtaylor/apisprout#15]
First of alll, thanks for this awesome tool!

Would be nice to have an endpoint, for instance **/__reload** which reloads the definition in case it was loaded via an URL. So it’s a kind of an workaround for watch mode on URLs

**Comment by danielgtaylor** [comment]
@timaschew what's the primary use-case for this feature? Is the idea to use it during development or to have a mock service updated as e.g. part of a deployment of the API description to some server? I assume in the second scenario you'd rather hit a URL than cycle the service?

**Comment by danielgtaylor** [comment]
I also wonder if this couldn't be accomplished on a cadence with an [If-Modified-Since](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Modified-Since) header (or the ETag equivalent). I'm also not opposed to a `/__reload` URL or something like it.

**Comment by timaschew** [comment]
> Is the idea to use it during development or to have a mock service updated as e.g. part of a deployment of the API description to some server?

It's the second case. Each time the spec is updated (merged into the master branch) the CI triggers the endpoint to reload the spec which is served via GitHub pages.

> I also wonder if this couldn't be accomplished on a cadence with an [If-Modified-Since](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Modified-Since) header (or the ETag equivalent)

So you want to check it on every request?
