### ISSUE TITLE
Catch invalid JSON errors in schemas when watching

### ISSUE THREAD

**Issue by jormaechea** [danielgtaylor/apisprout#27]
**Summary**
When mocking in watch mode, if the schema is not a valid JSON, the whole process exits with code 1 because of an uncaught error: `unexpected end of JSON input`

**Steps to reproduce**
Mock an invalid JSON schema. For example:
```
{"openapi": "3.0.0"
```

**Actual result**
The whole process (and the docker container) exit with an error code 1.

**Expected result**
The process should catch the error, show a controlled error message and keep watching changes until schema is a valid JSON.

**More info**
This happens if you edit the schema manually while watching, and save the file before you're done editing (this happens a lot when you have a continuoues-save-addiction in you).
Algo happens to me when syncing schemas from AWS S3 to my local machine (I guess it reads the file in the middle of the write operation).

**Comment by danielgtaylor** [comment]
This should be fixed in 5d19e0deb51a12ba6eebd5f0134f14a8cfff0403
