### ISSUE TITLE
Custom configuration for CORS headers

### ISSUE THREAD

**Issue by jormaechea** [danielgtaylor/apisprout#29]
**Summary**
CORS headers cannot be customized. As a consequence, we can't ser the `Access-Control-Allow-Credentials` header, nor set extra headers for `Access-Control-Allow-Headers`.

**Steps to reproduce**
Case 1: Mock any valid schema, and make a CORS request with a custom header such as `x-foo: bar`
Case 2: Mock any valid schema, and make a CORS request using `withCredentials` (https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials)

**Actual result**
The request fails indicating some of this errors, depending on the case:
Case 1: `[...] Request header field x-foo is not allowed by Access-Control-Allow-Headers in preflight response`
Case 2: `[...] Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute`

**Expected result**
The mock server should be able to:
1) Set/add allowed headers whether via configuration or API schema custom fields
2) Set CORS allow credentials property (in this case, it should set the header `Access-Control-Allow-Credentials: true`, and set the `Access-Control-Allow-Origin` with a dynamic value (with allow-credentials, origin cannot be a wildcard)

**Comment by danielgtaylor** [comment]
I've tested both cases with the latest code and can confirm they are now working as expected. Please let me know if you still want manual customization. For now the goal was to have it generally just work.
