### ISSUE TITLE
Unsupported format value 'int64'

### ISSUE THREAD

**Issue by mieszkomalawski** [danielgtaylor/apisprout#31]
Caught panic while trying to load: Validating Swagger failed: Unsupported 'format' value 'int6

int64 is valid Openapi format https://swagger.io/docs/specification/data-models/data-types/

**Comment by danielgtaylor** [comment]
@mieszkomalawski according to [the official spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#data-types) you are allowed to use a `format` of `int64` only when the `type` is `integer`.

If I make the `type` a `number` then I get the same error as you, but if I use `integer` then it works.

```sh
$ apisprout example-number.yaml
2019/03/12 21:52:21 Caught panic while trying to load: Validating Swagger failed: Unsupported 'format' value 'int64'

$ apisprout example-integer.yaml
🌱 Sprouting Example API on port 8000
```

Does that fix the problem?

**Comment by danielgtaylor** [comment]
I'm going to close this as I confirmed it does work with integers. Please reopen if needed!
