### ISSUE TITLE
URL required parameter is not validated correctly

### ISSUE THREAD

**Issue by aalmazanarbs** [danielgtaylor/apisprout#4]
Hi,

When I run APISprout with --validate-request and with the OPENAPI3.0 example:

[https://github.com/OAI/OpenAPI-Specification/raw/master/examples/v3.0/petstore.yaml](url)

and try to consume the endpoint /pets/{petId} I am getting the following error:

<img width="1167" alt="captura de pantalla 2018-09-07 a las 18 05 38" src="https://user-images.githubusercontent.com/25508559/45230266-a7031300-b2c8-11e8-921c-ca1f88c6e627.png">

As you can see the petId is present in the request url (SGTY56).

Regards.

**Comment by arthuroz** [comment]
PR created https://github.com/danielgtaylor/apisprout/pull/7

**Comment by FernandoBontorin** [comment]
you need to specify an example on the parameter {petId} like 'example: "SGTY56"' in YAML to works on OpenAPI3 lib parser and reflect on mock (apisprout)
